export const environment = {
    production: true,
    authKey: '54321',
    hospitalCode: 1,
    imgbbApi: 'b07dfc46f0f90cce9b2993d3b4896e80',
    location: 'পলাশপোল, সাতক্ষীরা।, শহীদ কাজল সরণী',
    baseApi: 'https://digital.supersoftbd.com/HWS',
    userApi: 'https://digital.supersoftbd.com/HWS/AspNetUserRoles/api',
    doctorApi: 'https://digital.supersoftbd.com/HWS/Doctor',
    userCode: 'DAa1*',
    rootApi: 'https://digital.supersoftbd.com/HWS',
    authApi: 'https://digital.supersoftbd.com/HWS/Authentication',
    DepartmentApi: 'https://digital.supersoftbd.com/HWS/Department',
    DoctorApi: 'https://digital.supersoftbd.com/HWS/Doctor',
    AboutApi: 'https://mec.supersoftbd.com/apiA/AboutUs',
    ContactApi: 'https://mec.supersoftbd.com/apiA/Address',
    CarouselApi: 'https://mec.supersoftbd.com/apiA/Carousel',
    emptyImg: 'https://www.mykite.in/kb/NoImageFound.jpg.png',
};