export const environment = {
  production: true,
  authKey: '1234',
  hospitalCode: 1,
  imgbbApi: 'b07dfc46f0f90cce9b2993d3b4896e80',
  location: 'পলাশপোল, সাতক্ষীরা।, শহীদ কাজল সরণী',
  userCode: 'DAa1*',
  baseApi: 'https://digital.supersoftbd.com/HWS',
  userApi: 'https://digital.supersoftbd.com/HWS/AspNetUserRoles/api',
  doctorApi: 'https://digital.supersoftbd.com/HWS/Doctor',
  rootApi: 'https://digital.supersoftbd.com/HWS',
  authApi: 'https://digital.supersoftbd.com/HWS/Authentication',
  DepartmentApi: 'https://digital.supersoftbd.com/HWS/Department',
  DoctorApi: 'https://digital.supersoftbd.com/HWS/Doctor',
  AboutApi: 'https://digital.supersoftbd.com/HWS/AboutUs',
  ContactApi: 'https://digital.supersoftbd.com/HWS/Address',
  CarouselApi: 'https://digital.supersoftbd.com/HWS/Carousel',
  emptyImg: 'https://www.mykite.in/kb/NoImageFound.jpg.png',
};
