export const environment = {
  production: true,
  authKey: '1234',
  hospitalCode: 1,
  imgbbApi: 'b07dfc46f0f90cce9b2993d3b4896e80',
  location: 'পলাশপোল, সাতক্ষীরা।, শহীদ কাজল সরণী',
  userCode: 'DAa1*',
  baseApi: '/HWS',
  userApi: '/apiA',
  doctorApi: '/HWS/Doctor',
  rootApi: '/HWS',
  authApi: '/HWS/Authentication',
  DepartmentApi: '/HWS/Department',
  DoctorApi: '/HWS/Doctor',
  AboutApi: '/HWS/AboutUs',
  ContactApi: '/HWS/Address',
  CarouselApi: '/HWS/Carousel',
  emptyImg: 'https://www.mykite.in/kb/NoImageFound.jpg.png',
};
